[#6] Feat: 헤더 컴포넌트 UI 구현
zzalmyu/zzalmyu-frontend pull request #13
Opened 2024-02-12 12:47 UTC by hyeonjinan096

## 📝 작업 내용

> 헤더 레이아웃을 구현했습니다. 
- 테마 토글 컴포넌트 
- 드롭다운 메뉴 
- 사용자 정보 별 렌더링 구현 (사용자 데이터의 형태에 따라 조건문 로직이 변경될 것 같습니다.)

> 드롭다운 메뉴에 아이콘 svg를 컴포넌트화해서 사용하려 했으나, vite+ts 환경에서는 vite-plugin-svgr 추가 설정이 필요한 거 같습니다. 추가 설정 없이 되시는 분이 있다면 알려주시면 감사할 것 같습니다. 우선 [프로젝트 세팅 Pr](https://github.com/zzalmyu/zzalmyu-frontend/pull/2) 코멘트에서 용재님께서 올려주신 [링크](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/pull/177/files#diff-f70545806014483abf5aca8f8d64c23235909da9b87826a1edd72f47b25335fe)를 참고하여 다음과 같이 설정 변경을 했습니다. 
올바른 설정인지 확인 부탁드립니다. 수정해야 하는 사항이 있다면 말씀해주세요.

- **tsconfig.json**에 `"types": ["vite-plugin-svgr/client"]` 추가
TypeScript가 svgr에 필요한 타입을 올바르게 이해할 수 있도록 타입을 정의했습니다.

- **svg**파일 import시 경로에 `?react` 추가
`import Heart from "@/assets/svg/heart.svg?react";`
?react를 통해 svgr이 SVG 파일을 변환하여 React 컴포넌트로 생성하도록 지정했습니다.

- **vit.config.ts**에 설정된 svgr 패턴을 비웠습니다. 
설정된 패턴과 사용하고자 하는 SVG파일의 경로 패턴이 일치하지 않는 경우가 발생해 제거했습니다. 
`svgr({  include: "*.svg",}),` -> `svgr(),`

> theme toggle 색상을 변경했습니다. 
> tailwind.config.js에 dark 모드 색이 다르게 기입된게 있는 거 같아 수정했습니다. (background, border)

### 📷 스크린샷 (선택)
![header_admin](https://github.com/zzalmyu/zzalmyu-frontend/assets/107539614/4527676f-d5cf-440c-9823-ac7a940cd310)

https://github.com/zzalmyu/zzalmyu-frontend/assets/107539614/88755f6c-6690-45e7-86af-25bb44f321d3

임시로 로그인 버튼을 누르면 사용자 정보가 회원으로 바뀌게 한 상태의 영상입니다. 해당 로직은 제거했습니다.
## 💬 리뷰 요구사항(선택)

- 컴포넌트명, 변수명을 적절하게 설정했는지 봐주시면 감사하겠습니다. 👍
- 그외에도 파일구조나 컨벤션 어긋나는 것이 있다면 말씀해주세요. 🙂

# 📍 기타 (선택)
svgr 설정 참고
- [Type definition for vite-plugin-svgr?](https://stackoverflow.com/questions/74720726/type-definition-for-vite-plugin-svgr)
- [Vite에서 svg를 ReactComponet로 가져오는 방법](https://velog.io/@woo9807/Vite-%EC%97%90%EC%84%9C-svg%EB%A5%BC-ReactComponet%EB%A1%9C-%EA%B0%80%EC%A0%B8%EC%98%A4%EB%8A%94-%EB%B0%A9%EB%B2%95)

close #6

2024-02-13 06:33 UTC, Kim-Jaemin420 reviewed
공통 헤더 컴포넌트라서 그런지 리뷰양이 조금 많네요ㅠㅠ여러 가지 이슈가 많았던 것 같은데 직접 찾아보시고 해결하시느라 고생 많으셨습니다 : )

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/DropdownMenu.tsx
> +                <a href={url}>
a 태그 사용하시면 리로드 일어나면서 화면 깜빡여요. 리액트에서는 Link 사용해주세요

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/DropdownMenu.tsx
> +                    <Icon size={20} />
아이콘이면 aria-label 넣어서 어떤 아이콘인지 명시해주시면 좋습니당
```js
<Icon aria-label="홈" />
```

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/index.tsx
common/Header/index.tsx가 되어야 할 것 같네요

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/ThemeToggle.tsx
> +        <input
여기에 input 태그를 사용하는게 적절하지 않은 것 같습니당! input 태그는 보통 form 태그와 함께 사용되며 제출하는 용도로 사용되는데 여기는 그렇지 않아서에용

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/DropdownMenu.tsx
> +const DropdownMenu = ({ user }: Props) => {
유저 정보를 props로 받을 필요는 없을 것 같긴 한데...우선 pseudo 코드라고 생각하고 넘어가겠습니당

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/DropdownMenu.tsx
> +      <li>
여기는 ul, li를 사용하지 않아도 될 것 같은데요?

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/DropdownMenu.tsx
> +              <li key={name} className="group ">
이렇게 고유값이 없는 list의 경우는 저희 컨벤션 정했던 것처럼 해주시면 더 좋을 것 같습니다 : )
```js
<li key={`${index}-${name}`}>
```

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/index.tsx
> +      <a href="/" className="btn btn-ghost flex items-center hover:bg-transparent">
마찬가지로 a 태그 없애주세용~: )

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/ThemeToggle.tsx
> +      localStorage.setItem("theme", theme);
로컬스토리지 유틸 함수 만들어 사용하면 좋을 것 같은데 이건 나중에 제가 할까요? 아니면 현진님이 하실래용? 편하게 말씀해주세여~~

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/ThemeToggle.tsx
> +    <label className="grid cursor-pointer place-items-center">
여기 스타일링을 그리드로 하셨는데, 우선은 flex로 해결할 수 있다면 flex로 해결하시고 안됐을때 grid 사용하는게 좋다고 배웠는데요,
뭔가 잘 안돼서 그리드 써주신건가용?

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/ThemeToggle.tsx
> +          checked={theme === "light" ? false : true}
이거 그냥 아래처럼 쓸 수 있지 않나요?
```js
checked={theme !== 'light'}
```

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/index.tsx
> +          <button className="btn btn-ghost pointer-events-none h-6 min-h-9">Admin</button>
Admin 눌렀을때 어드민 페이지로 이동하니 버튼보다는 링크가 맞는 것 같습니다 : )

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/index.tsx
> +        {user && !user.isAdmin && (
유저 role을 헤더에서 직접 검사하는게 마음에 걸리네요..우선 로직 구현이 안됐으니 pseudo 코드라 생각하고 넘어가겠습니당! 추후 개선해봐요

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/index.tsx
> +          <button className="btn h-9 min-h-9 border-primary bg-primary text-white hover:bg-gray-300">
클릭시 업로드 페이지로 이동하게 되어서 Link태그를 사용하거나 button을 link로 감싸는게 좋을 것 같네요!

2024-02-13 06:33 UTC, Kim-Jaemin420 commented on src/components/Common/ThemeToggle.tsx
> +          <Moon size={14} strokeWidth={2.2} color="white" />
아이콘들에게는 aria-label 잊지마세용!!

2024-02-13 08:57 UTC, hyeonjinan096 commented on src/components/Common/DropdownMenu.tsx
> +                <a href={url}>
Link태그 사용하기 위해서 `RouterProvider`설정이 있어야하는 것 같습니다. 메인 페이지에 머지 후 연결해도 될까요?

2024-02-13 09:02 UTC, hyeonjinan096 commented on src/components/Common/index.tsx
> +          <button className="btn h-9 min-h-9 border-primary bg-primary text-white hover:bg-gray-300">
현재 브랜치에 RouterProvider설정이 없어 link를 사용하면 에러가 뜨는데 메인 페이지에 머지 후 연결해서 확인해봐도 될까요?

2024-02-13 09:04 UTC, yjc2021 reviewed
수고하셨습니다 현진님! PR 후에 코드 업뎃을 하셔서 일단 이전 버전 리뷰부터 남길게요! 
현재 색상 토큰 정책이 업데이트가 안 된 것 같아서 먼저 한번 main을 pull하시고 브랜치에 머지해주셔야 할 것 같습니다 :)

2024-02-13 09:04 UTC, yjc2021 commented on tailwind.config.js
> -          "--toggle-center": "254, 229, 0",
현진님 한번 main 브랜치 pull 받고 main을 merge해야 할 것 같습니다! 수정된 색상 토큰 정책이 반영이 안 된 버전으로 작업하신 것 같아요!

2024-02-13 09:04 UTC, yjc2021 commented on src/components/Common/ThemeToggle.tsx
> +        <input
이건 현진님이 [daisyUI toggle](https://daisyui.com/components/toggle/) 참고하신 것 같습니다! 
아마 checkbox를 활용한 css trick이 있어서 daisy에서 이렇게 만든 것 같네요 😸

2024-02-13 09:08 UTC, hyeonjinan096 commented on tailwind.config.js
> -          "--toggle-center": "254, 229, 0",
네 pull 후에 작업 다시 하겠습니다!

2024-02-13 09:39 UTC, choi-ik requested changes
공통 컴포넌트 구현하시느라 고생 많으셨습니다 현진님~~! 간단한 리뷰 남겨드렸으니 확인 부탁드립니다 ㅎㅎㅎ 👯

2024-02-13 09:39 UTC, choi-ik commented on src/components/common/Header/ThemeToggle.tsx
> +      document.querySelector("html")?.setAttribute("data-theme", localTheme || "light");
html 태그가 존재 하지 않을 상황이 어떤 상황이 있을까 고민해보다 없을 것 같다는 생각이 드는데요! 그래서 옵셔널 체이닝이 없어도 될 것 같다는 생각이 드는데 현진님은 어떠신가요?!? 🤔🤔

2024-02-13 09:39 UTC, choi-ik commented on src/components/common/Header/index.tsx
> +        {!user && <button className="btn btn-ghost h-6 min-h-9">로그인</button>}
여기서 user에 대한 체크는 로그인 여부인가요 현진님??!

2024-02-13 10:06 UTC, hyeonjinan096 commented on src/components/common/Header/index.tsx
> +        {!user && <button className="btn btn-ghost h-6 min-h-9">로그인</button>}
네 맞습니다! 로그인 안했을시에 user가 null인걸로 가정했습니다. 해당 로직은 추후 데이터 형태에 따라 변경될 것 같습니다.

2024-02-13 10:12 UTC, hyeonjinan096 commented on src/components/common/Header/ThemeToggle.tsx
> +      document.querySelector("html")?.setAttribute("data-theme", localTheme || "light");
처음에 옵셔널 체이닝 없이 작성을 했는데 `Object is possibly 'null'.` 이라는 타입에러가 떠서 추가했습니다. 다른 방법있을까요? 저도 html태그가 존재하지 않을 상황이 딱히 생각나지는 않네요.🥲

2024-02-13 10:47 UTC, hyeonjinan096 commented on src/components/Common/ThemeToggle.tsx
> +        <input
데이지 UI 토글을 참고했습니다. 제공해주는 토글 동작 자체가 input태그 기반으로 설계되어있는 거 같습니다.🥲

2024-02-13 11:24 UTC, Kim-Jaemin420 commented on src/components/Common/ThemeToggle.tsx
> +        <input
으아 그렇군요ㅠㅠ죄송합니다 어쩔 수 없겠네여

2024-02-13 11:31 UTC, Kim-Jaemin420 commented on src/components/common/Header/DropdownMenu.tsx
> +                <Link href={url}>
Link에는 to 사용해주셔야 할 것 같아요! : D

2024-02-13 11:46 UTC, hyeonjinan096 commented on src/components/Common/DropdownMenu.tsx
> +      <li>
드랍다운 메뉴도 daisy에 있는 코드를 활용했습니다. 
ul태그는 div로 변경이 가능한데 list를 div로 변경하면 드랍다운 css속성이 다 날라가네요ㅠ 
daisy 드랍다운 메뉴 중에 div로 감싸진 코드도 있는데
와이어 프레임과 같이 클릭시에 화살표가 위아래로 움직이는 드랍다운 메뉴는 list로 감싸서 작동합니다.🥲

2024-02-13 11:55 UTC, yjc2021 reviewed
최신 버전에 대한 리뷰가 좀 늦어졌네요ㅠ 고생하셨습니다 :)

2024-02-13 11:55 UTC, yjc2021 commented on src/components/common/Header/ThemeToggle.tsx
> +          <SunDim size={16} strokeWidth={2} color="white" />
현진님 toggle 색상 중에 안 쓰이는 색상들 알려주시면 제거해 놓도록 하겠습니다 👍

2024-02-13 11:55 UTC, yjc2021 commented on src/components/common/Header/index.tsx
> +        <div className="h-6 w-0.5 bg-gray-400"></div>
라이트/다크 모드 고려해서 tailwind config에 등록된 색상을 사용해주세요! (헤더의 text와 동일한 색상 쓰시면 될 것 같아요)

2024-02-13 11:55 UTC, yjc2021 commented on src/components/common/Header/ThemeToggle.tsx
> +        <div className="absolute flex w-auto items-center gap-2.5 px-1 py-1">
`px-1 py-1`은 `p-1`로 축약할 수 있을 것 같아요 :)

2024-02-13 11:55 UTC, yjc2021 commented on src/components/common/Header/ThemeToggle.tsx
> +  useEffect(() => {
해당 부분은 별도의 hook으로 분리하는 게 코드 가독성에 좋을 것 같아요 :)

2024-02-13 11:55 UTC, yjc2021 commented on src/components/common/Header/DropdownMenu.tsx
> +    <ul className="menu menu-horizontal px-0 ">
`ul`보다는 `div`가 적절할 것 같아요 :)

2024-02-13 11:55 UTC, yjc2021 commented on src/components/common/Header/DropdownMenu.tsx
> +        <details>
제가 잘 몰라서 그러는데 [dropdown ](https://daisyui.com/components/dropdown/#dropdown-in-navbar) 말고 [menu](https://daisyui.com/components/menu/) 를 쓰신 이유가 있을까요?

2024-02-13 11:59 UTC, Kim-Jaemin420 commented on src/components/common/Header/DropdownMenu.tsx
> +interface Props {
import 구문이랑 interface 는 줄 간격 둬서 구분해주시면 좋습니다ㅎㅎ~~: D

2024-02-13 11:59 UTC, Kim-Jaemin420 commented on src/components/common/Header/DropdownMenu.tsx
> +      url: "/my-uploaded-zzal/",
url은 www.~라서 path라는 이름이 더 적절할 것 같아요! 이제서야 보이네요ㅠㅠ

2024-02-13 11:59 UTC, Kim-Jaemin420 commented on src/components/common/Header/DropdownMenu.tsx
> +            {menuItems.map(({ url, icon: Icon, name }, index) => (
근데 여기서 icon을 rename 하지말고 객체에서 Icon으로 받으면 안되나요?
```js
    {
      url: "/",
      Icon: LogOut,
      name: "로그아웃",
    },

```

2024-02-13 11:59 UTC, Kim-Jaemin420 commented on src/components/common/Header/ThemeToggle.tsx
> +        <div className="absolute flex w-auto items-center gap-2.5 px-1 py-1">
오 매의 눈인디

2024-02-13 11:59 UTC, Kim-Jaemin420 commented on src/components/common/Header/index.tsx
> +        <Logo />
여기두 aria label 달아주쎄용~~: D

2024-02-13 11:59 UTC, Kim-Jaemin420 commented on src/components/common/Header/index.tsx
> +          <Link to={"/upload-zzal/"}>
문자열이면 중괄호 빼도 돼용!! 위에도 빼주세여 : )

2024-02-13 12:02 UTC, Kim-Jaemin420 commented on src/components/common/Header/ThemeToggle.tsx
> +  useEffect(() => {
흠 이거 저는 훅으로 분리하기에는 여기서만 사용될 것 같아서요, 그래서 해당 컴포넌트에서 분리해내면 오히려 응집도가 떨어지고 한 뎁스 더 들어가야 해서 코드 읽기도 어려워질 것 같다는 생각이 드네용🤔

제 생각이 정답은 아니고 하나의 의견입니당! 가볍게 들어주세여~~

2024-02-13 12:35 UTC, hyeonjinan096 commented on src/components/common/Header/DropdownMenu.tsx
> +        <details>
daisyui에서 드롭다운 메뉴를 포함한 navabar 컴포넌트를 제공해줘서 이를 활용한 것입니다. 별도의 dropdown메뉴에는 화살표가 없어 사용하지 않았습니당

2024-02-13 12:41 UTC, hyeonjinan096 commented on src/components/Common/ThemeToggle.tsx
> +    <label className="grid cursor-pointer place-items-center">
데이지 ui활용 코드인데 해당 속성을 지워도 아무변화가 없어 제거했습니다!

2024-02-13 12:42 UTC, hyeonjinan096 commented on src/components/common/Header/DropdownMenu.tsx
> +    <ul className="menu menu-horizontal px-0 ">
드롭다운 메뉴도 daisy에 있는 코드를 활용했습니다.
ul태그는 div로 변경이 가능한데 list를 div로 변경하면 드롭다운 css속성이 다 날라가네요ㅠ

2024-02-13 12:54 UTC, Kim-Jaemin420 commented on src/components/common/Header/index.tsx
> +        <Logo aria-label={"짤뮤니티 로고"} />
진짜 찐막...중괄호 지워주시면 감사하겠습니다ㅎㅎㅎ이것만 되면 approve 갈게요!

2024-02-13 12:59 UTC, thalassophilia approved these changes
많은 리뷰 다 커버하시느라 고생 많으셨습니다!

2024-02-14 02:34 UTC, choi-ik approved these changes
고생하셨씁니다 현진님!!!💪💪

2024-02-14 02:38 UTC, merged