[#249] Refactor: 쿼리들을 효율적으로 관리할 수 있도록 queryOptions 객체를 사용하여 co-location 하는 방식으로 리팩토링
zzalmyu/zzalmyu-frontend pull request #252
Opened 2024-07-26 10:26 UTC by choi-ik

## 📝 작업 내용

TanStack Query의 쿼리들을 효율적으로 관리하고 유지보수 할 수 있도록 `QueryOptions/InfiniteQueryOptions`를 사용하여 `co-location` 하는 방식으로 수정하였습니다.

- 현재 아직 Next.js로 마이그레이션 작업이 진행중이라 수정한 쿼리문을 각각의 사용처에 적용하지는 않았습니다. 
- 또한 `QueryOptions/InfiniteQueryOptions`을 사용함으로써 중복되는 파일들을 아직 제거하지 않았습니다. 아직 도메인 변경 후 변경된 도메인 주소가 배포에 반영되지 않아 API Request를 테스트해 볼 수 없고, 마이그레이션 하는데도 혼선이 있을 것 같아 그대로 두었습니다.

추후, NextJS 마이그레이션과 변경된 도메인이 반영이 되면, 그때 중복되는 코드들을 지우고 구현한 `QueryKeyFactories`를 사용하도록 페이지들을 수정할 예정입니다.

### 📷 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

- `hooks/api` 각각의 파일 내에 `queryKeyFactories`라는 네이밍을 지었는데 네이밍이 적절한지 궁금합니다.
- `queryKeyFactories` 내에 정의된 `queryKey`와 `api Request` 네이미잉 적절한지 궁금합니다.

# 📍 기타 (선택)

> 다른 분들이 참고해야할 사항이 있다면 작성해주세요

close #249

2024-07-28 02:33 UTC, yjc2021 requested changes
익님 수고하셨습니다~
- 요청하신대로 네이밍 관련해서 피드백 드렸습니다!
- 또한 각 팩토리의 .all 프로퍼티를 정의하는 방식에 대해서 궁금한 점도 코멘트로 남겼습니다! 같이 얘기해보시죠 :)

2024-07-28 02:33 UTC, yjc2021 commented on src/hooks/api/zzal/queryKeyFactories.ts
> +  myUploadedZzlasKey: () => [...zzalQueries.all(), "uploadedZzals"] as const,
오타가 있네요
`myUploadedZzalsKey`로 수정하면 좋을 것 같아요!

2024-07-28 02:33 UTC, yjc2021 commented on src/hooks/api/zzal/queryKeyFactories.ts
> +  all: () => ["zzal"] as const,
`zzalQueries.all`을 함수로 정의한 이유가 무엇인지 궁금합니다!
`all: [''zzal''] as const` 로 지정하면 zzalQueries.all 값을 가져올 때 함수 호출 없이 프로퍼티 참조처럼 가져올 수 있는데 두 방식의 차이점이 있을까요?

2024-07-28 02:33 UTC, yjc2021 commented on src/hooks/api/zzal/queryKeyFactories.ts
> +      queryKey: [...zzalQueries.myUploadedZzlasKey(), selectedTags] as const,
`myUploadedZzalsKey()` 로 수정 부탁드립니다!

2024-07-28 02:33 UTC, yjc2021 commented on src/hooks/api/tag/queryKeyFactories.ts
> +  all: () => ["tags"] as const,
`tag`로 단수는 어떨까요? 나머지 팩토리들에서 단수형을 사용하셔서 통일하면 좋을 것 같습니다!

2024-07-28 07:50 UTC, choi-ik commented on src/hooks/api/zzal/queryKeyFactories.ts
> +  all: () => ["zzal"] as const,
아 큰 차이점은 없습니다! 다른 프로퍼티들도 함수로 정의하다보니 통일성 때문에 `all` 프로퍼티도 함수로 작성한 것 같은데 굳이 함수로 작성할 필요가 없었던 것 같네요 ㅎㅎ 다른 `queryKeyFactories` 들도 정적으로 생성할 수 있게 수정하는게 사용하는 입장에서 더욱 편할 것 같네요 ㅎㅎ

2024-07-28 07:51 UTC, choi-ik commented on src/hooks/api/tag/queryKeyFactories.ts
> +  all: () => ["tags"] as const,
좋습니다! 단수형으로 통일하려했는데 태그 부분은 실수했네요 💦

2024-07-29 11:03 UTC, yjc2021 approved these changes

2024-07-29 14:46 UTC, merged